# general settings
name: train_REDS_v1
model_type: VideoCompressRecurrentModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSCompressRecurrentDataset
    val_partition: REDS4
    dataroot_gt: datasets/REDS/gt
    dataroot_lq: datasets/REDS/lq
    lq_subroot:  [BI, CRF_15, CRF_25, CRF_35]    #[BI, BI, BI, CRF_15, CRF_25, CRF_35]
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    io_backend:
      type: disk

    num_frame: 7
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: false # true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: ~
#
  val_15:
    name: REDS4_crf15
    type: VideoCompressRecurrentTestDataset
    dataroot_gt: datasets/REDS4/gt
    dataroot_lq: datasets/REDS4/lq/CRF_15
    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed

  val_25:
    name: REDS4_crf25
    type: VideoCompressRecurrentTestDataset
    dataroot_gt: datasets/REDS4/gt
    dataroot_lq: datasets/REDS4/lq/CRF_25
    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed
#
  val_35:
    name: REDS4_crf25
    type: VideoCompressRecurrentTestDataset
    dataroot_gt: datasets/REDS4/gt
    dataroot_lq: datasets/REDS4/lq/CRF_35

    cache_data: True
    io_backend:
      type: disk
    num_frame: -1  # not needed

# network structures
network_g:
  type: CEAVSR
  spynet_pretrained: /home/jq/Compression/CAVSR-master/checkpoints/spynet_20210409-c6c1bd09.pth


# path
path:
  pretrain_network_g: /home/jq/Compression/CAVSR-master/checkpoints/net_g_19000.pth
  strict_load_g: true
  resume_state: ~ #/home/jq/Compression/CAVSR-master/experiments/train_REDS/training_states/2000.state

# training settings
train:
#  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000, 100000, 100000, 100000]
    restart_weights: [1.0, 1.0, 1.0, 1.0]
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
#    loss_weight: [0.5, 0.25, 0.25]
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
#  wandb:
#    project: vsr_best
#    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
